version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: todolist-mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: todolist
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: Admin123

volumes:
  mysqldata:
